import * as z from "zod";

/** Portable configuration exports never contain secrets. */
export const ConfigurationTomlOutputSchema = z.object({
  toml: z.string(),
});

export const ConfigurationJsonOutputSchema = z.object({
  json: z.string(),
});

/**
 * Source tokens generated by an import are returned once, so the operator can
 * wire the upstream systems that were just re-created.
 */
export const ImportConfigurationOutputSchema = z.object({
  generatedSourceTokens: z.array(
    z.object({
      sourceId: z.string().min(1),
      sourceName: z.string().min(1),
      token: z.string().min(1),
    }),
  ),
});

