/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SetupRouteImport } from "./routes/setup";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as DashboardRouteImport } from "./routes/_dashboard";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ApiReadyRouteImport } from "./routes/api/ready";
import { Route as ApiHealthRouteImport } from "./routes/api/health";
import { Route as DashboardSourcesRouteImport } from "./routes/_dashboard.sources";
import { Route as DashboardSettingsRouteImport } from "./routes/_dashboard.settings";
import { Route as DashboardRoutesRouteImport } from "./routes/_dashboard.routes";
import { Route as DashboardEventsRouteImport } from "./routes/_dashboard.events";
import { Route as DashboardDestinationsRouteImport } from "./routes/_dashboard.destinations";
import { Route as DashboardDeliveriesRouteImport } from "./routes/_dashboard.deliveries";
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth/$";
import { Route as DashboardEventsEventIdRouteImport } from "./routes/_dashboard.events_.$eventId";
import { Route as DashboardDeliveriesDeliveryIdRouteImport } from "./routes/_dashboard.deliveries_.$deliveryId";
import { Route as ApiSourcesSourceIdWebhookRouteImport } from "./routes/api/sources/$sourceId/webhook";

const SetupRoute = SetupRouteImport.update({
  id: "/setup",
  path: "/setup",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
  id: "/_dashboard",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiReadyRoute = ApiReadyRouteImport.update({
  id: "/api/ready",
  path: "/api/ready",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: "/api/health",
  path: "/api/health",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardSourcesRoute = DashboardSourcesRouteImport.update({
  id: "/sources",
  path: "/sources",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardRoutesRoute = DashboardRoutesRouteImport.update({
  id: "/routes",
  path: "/routes",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardEventsRoute = DashboardEventsRouteImport.update({
  id: "/events",
  path: "/events",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardDestinationsRoute = DashboardDestinationsRouteImport.update({
  id: "/destinations",
  path: "/destinations",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardDeliveriesRoute = DashboardDeliveriesRouteImport.update({
  id: "/deliveries",
  path: "/deliveries",
  getParentRoute: () => DashboardRoute,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardEventsEventIdRoute = DashboardEventsEventIdRouteImport.update({
  id: "/events_/$eventId",
  path: "/events/$eventId",
  getParentRoute: () => DashboardRoute,
} as any);
const DashboardDeliveriesDeliveryIdRoute =
  DashboardDeliveriesDeliveryIdRouteImport.update({
    id: "/deliveries_/$deliveryId",
    path: "/deliveries/$deliveryId",
    getParentRoute: () => DashboardRoute,
  } as any);
const ApiSourcesSourceIdWebhookRoute =
  ApiSourcesSourceIdWebhookRouteImport.update({
    id: "/api/sources/$sourceId/webhook",
    path: "/api/sources/$sourceId/webhook",
    getParentRoute: () => rootRouteImport,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/setup": typeof SetupRoute;
  "/deliveries": typeof DashboardDeliveriesRoute;
  "/destinations": typeof DashboardDestinationsRoute;
  "/events": typeof DashboardEventsRoute;
  "/routes": typeof DashboardRoutesRoute;
  "/settings": typeof DashboardSettingsRoute;
  "/sources": typeof DashboardSourcesRoute;
  "/api/health": typeof ApiHealthRoute;
  "/api/ready": typeof ApiReadyRoute;
  "/deliveries/$deliveryId": typeof DashboardDeliveriesDeliveryIdRoute;
  "/events/$eventId": typeof DashboardEventsEventIdRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/sources/$sourceId/webhook": typeof ApiSourcesSourceIdWebhookRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/setup": typeof SetupRoute;
  "/deliveries": typeof DashboardDeliveriesRoute;
  "/destinations": typeof DashboardDestinationsRoute;
  "/events": typeof DashboardEventsRoute;
  "/routes": typeof DashboardRoutesRoute;
  "/settings": typeof DashboardSettingsRoute;
  "/sources": typeof DashboardSourcesRoute;
  "/api/health": typeof ApiHealthRoute;
  "/api/ready": typeof ApiReadyRoute;
  "/deliveries/$deliveryId": typeof DashboardDeliveriesDeliveryIdRoute;
  "/events/$eventId": typeof DashboardEventsEventIdRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/sources/$sourceId/webhook": typeof ApiSourcesSourceIdWebhookRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_dashboard": typeof DashboardRouteWithChildren;
  "/login": typeof LoginRoute;
  "/setup": typeof SetupRoute;
  "/_dashboard/deliveries": typeof DashboardDeliveriesRoute;
  "/_dashboard/destinations": typeof DashboardDestinationsRoute;
  "/_dashboard/events": typeof DashboardEventsRoute;
  "/_dashboard/routes": typeof DashboardRoutesRoute;
  "/_dashboard/settings": typeof DashboardSettingsRoute;
  "/_dashboard/sources": typeof DashboardSourcesRoute;
  "/api/health": typeof ApiHealthRoute;
  "/api/ready": typeof ApiReadyRoute;
  "/_dashboard/deliveries_/$deliveryId": typeof DashboardDeliveriesDeliveryIdRoute;
  "/_dashboard/events_/$eventId": typeof DashboardEventsEventIdRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/api/sources/$sourceId/webhook": typeof ApiSourcesSourceIdWebhookRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/login"
    | "/setup"
    | "/deliveries"
    | "/destinations"
    | "/events"
    | "/routes"
    | "/settings"
    | "/sources"
    | "/api/health"
    | "/api/ready"
    | "/deliveries/$deliveryId"
    | "/events/$eventId"
    | "/api/auth/$"
    | "/api/sources/$sourceId/webhook";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/login"
    | "/setup"
    | "/deliveries"
    | "/destinations"
    | "/events"
    | "/routes"
    | "/settings"
    | "/sources"
    | "/api/health"
    | "/api/ready"
    | "/deliveries/$deliveryId"
    | "/events/$eventId"
    | "/api/auth/$"
    | "/api/sources/$sourceId/webhook";
  id:
    | "__root__"
    | "/"
    | "/_dashboard"
    | "/login"
    | "/setup"
    | "/_dashboard/deliveries"
    | "/_dashboard/destinations"
    | "/_dashboard/events"
    | "/_dashboard/routes"
    | "/_dashboard/settings"
    | "/_dashboard/sources"
    | "/api/health"
    | "/api/ready"
    | "/_dashboard/deliveries_/$deliveryId"
    | "/_dashboard/events_/$eventId"
    | "/api/auth/$"
    | "/api/sources/$sourceId/webhook";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  DashboardRoute: typeof DashboardRouteWithChildren;
  LoginRoute: typeof LoginRoute;
  SetupRoute: typeof SetupRoute;
  ApiHealthRoute: typeof ApiHealthRoute;
  ApiReadyRoute: typeof ApiReadyRoute;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
  ApiSourcesSourceIdWebhookRoute: typeof ApiSourcesSourceIdWebhookRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/setup": {
      id: "/setup";
      path: "/setup";
      fullPath: "/setup";
      preLoaderRoute: typeof SetupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_dashboard": {
      id: "/_dashboard";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/ready": {
      id: "/api/ready";
      path: "/api/ready";
      fullPath: "/api/ready";
      preLoaderRoute: typeof ApiReadyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/health": {
      id: "/api/health";
      path: "/api/health";
      fullPath: "/api/health";
      preLoaderRoute: typeof ApiHealthRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_dashboard/sources": {
      id: "/_dashboard/sources";
      path: "/sources";
      fullPath: "/sources";
      preLoaderRoute: typeof DashboardSourcesRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/settings": {
      id: "/_dashboard/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof DashboardSettingsRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/routes": {
      id: "/_dashboard/routes";
      path: "/routes";
      fullPath: "/routes";
      preLoaderRoute: typeof DashboardRoutesRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/events": {
      id: "/_dashboard/events";
      path: "/events";
      fullPath: "/events";
      preLoaderRoute: typeof DashboardEventsRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/destinations": {
      id: "/_dashboard/destinations";
      path: "/destinations";
      fullPath: "/destinations";
      preLoaderRoute: typeof DashboardDestinationsRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/deliveries": {
      id: "/_dashboard/deliveries";
      path: "/deliveries";
      fullPath: "/deliveries";
      preLoaderRoute: typeof DashboardDeliveriesRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_dashboard/events_/$eventId": {
      id: "/_dashboard/events_/$eventId";
      path: "/events/$eventId";
      fullPath: "/events/$eventId";
      preLoaderRoute: typeof DashboardEventsEventIdRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/_dashboard/deliveries_/$deliveryId": {
      id: "/_dashboard/deliveries_/$deliveryId";
      path: "/deliveries/$deliveryId";
      fullPath: "/deliveries/$deliveryId";
      preLoaderRoute: typeof DashboardDeliveriesDeliveryIdRouteImport;
      parentRoute: typeof DashboardRoute;
    };
    "/api/sources/$sourceId/webhook": {
      id: "/api/sources/$sourceId/webhook";
      path: "/api/sources/$sourceId/webhook";
      fullPath: "/api/sources/$sourceId/webhook";
      preLoaderRoute: typeof ApiSourcesSourceIdWebhookRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

interface DashboardRouteChildren {
  DashboardDeliveriesRoute: typeof DashboardDeliveriesRoute;
  DashboardDestinationsRoute: typeof DashboardDestinationsRoute;
  DashboardEventsRoute: typeof DashboardEventsRoute;
  DashboardRoutesRoute: typeof DashboardRoutesRoute;
  DashboardSettingsRoute: typeof DashboardSettingsRoute;
  DashboardSourcesRoute: typeof DashboardSourcesRoute;
  DashboardDeliveriesDeliveryIdRoute: typeof DashboardDeliveriesDeliveryIdRoute;
  DashboardEventsEventIdRoute: typeof DashboardEventsEventIdRoute;
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDeliveriesRoute: DashboardDeliveriesRoute,
  DashboardDestinationsRoute: DashboardDestinationsRoute,
  DashboardEventsRoute: DashboardEventsRoute,
  DashboardRoutesRoute: DashboardRoutesRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardSourcesRoute: DashboardSourcesRoute,
  DashboardDeliveriesDeliveryIdRoute: DashboardDeliveriesDeliveryIdRoute,
  DashboardEventsEventIdRoute: DashboardEventsEventIdRoute,
};

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiReadyRoute: ApiReadyRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiSourcesSourceIdWebhookRoute: ApiSourcesSourceIdWebhookRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
